---
- name: Check CPU Affinity for mme llb
  hosts: remote_machines
  gather_facts: no
  vars_files:
    - vars_working.yml
  tasks:
    - name: Get k8s nodes
      raw: "taskset -cp 1"
      register: cpu_affinity_output

    - name: STATUS
      debug:
        msg:
          GENERATE_EVENT: "{{ cpu_affinity_output.stdout | length == 0 }}"
          Additional Info: "{{ [{'CHECK': 'K8s CPU Affinity check', 'Status': (cpu_affinity_output.stdout | length > 0) | ternary('OK', 'NOK')}] | to_json }}"
