---
- name: Check K8s HSS GTRE Provisioning API
  hosts: remote_machines
  tasks:
    - name: Get tun IP
      shell: /usr/sbin/ip a | grep tun | grep inet | awk '{print $2}' | cut -d"/" -f1
      register: tun_ip

    - name: Print read_shm_output
      debug:
        var: tun_ip

    - name: Set status
      set_fact:
        status: "{{ 'OK' if tun_ip.stdout.strip() else 'NOK' }}"

    - name: Set status
      set_fact:
        additional_info: "{{ tun_ip.stdout if status == 'OK' else '' }}"

    - name: Print STATUS
      debug:
        msg:
          GENERATE_EVENT: "{{ status == 'NOK' }}"
          Additional Info: "{{ [{'CHECK': 'K8s HSS GTRE Provisioning API test', 'STATE': status, 'INFO': additional_info}] | to_json }}"
