---
- name: "{{ EID_005_DESCRIPTION }}"
  hosts: remote_machines
  gather_facts: no
  vars_files:
    - vars_working.yml

  tasks:
    - name: Get current date
      raw: kubectl exec {{ pod_name }} -n {{ namespace }} -- date +"%Y-%m-%d %H:%M:%S"
      register: current_date

    - name: Get warm process state
      raw: kubectl exec {{ pod_name }} -n {{ namespace }} -- {{ EID_005_CMD }}
      register: process_state

    - name: Print warm process state
      debug:
        var: process_state.stdout_lines

    - name: Calculate generate_event
      set_fact:
        generate_event: "{{ ((current_date.stdout | regex_replace('\\s+$', '') | to_datetime('%Y-%m-%d %H:%M:%S')) - (process_state.stdout_lines | map('regex_search', '\\w+ \\w+ \\d+ \\d+:\\d+:\\d+ \\d+') | map('to_datetime', '%a %b %d %H:%M:%S %Y') | min)).total_seconds() / 60 < WARM_THRESHOLD_MIN }}"

    - name: STATUS
      debug:
        msg:
          {
            "GENERATE_EVENT": "{{ generate_event }}",
            "Additional Info": "{{ 'Warm process time less than threshold' if generate_event else '' }}"
          }
