---
- name: "{{ EID_007_DESCRIPTION }}"
  hosts: remote_machines
  gather_facts: no
  vars_files:
    - vars_working.yml

  tasks:
    - name: Get disk space
      raw: kubectl exec {{ pod_name }} -n {{ namespace }} -- {{ EID_007_CMD }}
      register: disk_space

    - name: Set generate_event and additional_info
      set_fact:
        generate_event: "{{ item.split()[4] | regex_replace('%', '') | int > VOLUME_SIZE_THRESHOLD }}"
        additional_info: "{{ item.split()[5] }} => {{ item.split()[4] }} used, exceeding threshold of {{ VOLUME_SIZE_THRESHOLD }} % "
      loop: "{{ disk_space.stdout_lines[1:] }}"
      when: item.split()[5] not in CHECK_07_IGNORE_PARTITIONS.split(',')
      register: disk_space_result

    - name: Set final generate_event and additional_info
      set_fact:
        final_generate_event: "{{ true in disk_space_result.results | map(attribute='ansible_facts.generate_event') }}"
        final_additional_info: >-
          [
          {% for result in disk_space_result.results %}
            {% if result.ansible_facts.generate_event %}
            {{ result.ansible_facts.additional_info }}
            {% endif %}
          {% endfor %}
          ]

    - name: STATUS
      debug:
        msg:
          {
            "GENERATE_EVENT": "{{ final_generate_event }}",
            "Additional Info": "{{ final_additional_info if final_generate_event else [] }}"
          }
