---
- name: "{{ EID_002_DESCRIPTION }}"
  hosts: remote_machines
  gather_facts: no
  vars_files:
    - vars_working.yml
  tasks:
    - name: Executing Command
      raw: kubectl exec {{ pod_name_cms }} -n {{ namespace_cms }} -- {{ EID_002_CMD }}
      register: cmdOutput

    - name: Printing command output
      debug:
        msg: "command output = {{ cmdOutput.stdout }}"

    - name: Extract values from output
      set_fact:
        extracted_values: "{{ cmdOutput.stdout | regex_findall(\"'([^']+)':'([^']+)'\") | items2dict(key_name=0, value_name=1) }}"

    - name: Check services status
      set_fact:
        not_running_services: "{{ cmdOutput.stdout | regex_findall('(.*) running \\[(?!OK).*\\]') }}"

    - name: Check values
      set_fact:
        generate_event: "{{ (extracted_values['ha_mode'] != 'Active') or (extracted_values['op_state'] != 'Configured') or (not_running_services | length > 0) }}"
      register: check_results

    - name: STATUS
      debug:
        msg:
          {
            "GENERATE_EVENT": "{{ check_results.ansible_facts.generate_event }}",
            "Additional Info": "{{ 'ha_mode or op_state is incorrect' if check_results.ansible_facts.generate_event and (extracted_values['ha_mode'] != 'Active' or extracted_values['op_state'] != 'Configured') else 'Not all services are running' if check_results.ansible_facts.generate_event and not_running_services | length > 0 else '' }}"
          }
