---
- name: Tunnel Check
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars_working.yml

  tasks:
    - name: Get readShm output
      raw: "kubectl exec -n {{ namespace }} {{ item }} -- /usr/IMS/current/bin/readShm 2>/dev/null"
      loop: "{{ pods }}"
      loop_control:
        loop_var: item
      register: read_shm_output

    - name: Check ip a output
      raw: "kubectl exec -n {{ namespace }} {{ item.item }} -- ip a"
      loop: "{{ read_shm_output.results }}"
      loop_control:
        loop_var: item
      when: item.stdout is search('vnfcHAMode\\s*:\\s*ACTIVE')
      register: ip_a_output

    - name: STATUS
      set_fact:
        additional_info: "{{ additional_info | default([]) + [ {'Pod': item.item.item, 'Tunnel Status': (item.stdout | regex_search('tun') | length > 0) | ternary('OK', 'NOK')}] }}"
      loop: "{{ ip_a_output.results }}"
      loop_control:
        loop_var: item

    - name: Print STATUS
      debug:
        msg:
          GENERATE_EVENT: "{{ additional_info | selectattr('Tunnel Status', 'match', 'NOK') | list | length > 0 }}"
          Additional Info: "{{ [{'CHECK': 'Tunnel check', 'STATE': (additional_info | selectattr('Tunnel Status', 'match', 'NOK') | list | length > 0) | ternary('NOK', 'OK'), 'INFO': additional_info | selectattr('Tunnel Status', 'match', 'NOK') | list}] | to_json }}"
