---
- name: "{{ EID_001_DESCRIPTION }}"
  hosts: remote_machines
  gather_facts: no
  vars_files:
    - vars_working.yml
  vars:
    ansible_python_interpreter: /usr/bin/python3.6
  tasks:
    - name: Executing Command
      shell: kubectl exec {{ pod_name }} -n {{ namespace }} -- {{ EID_001_CMD }}
      #raw: kubectl exec {{ pod_name }} -n {{ namespace }} -- {{ EID_001_CMD }}
      register: cmdOutput

    - name: Printing command output
      debug:
        msg: "command output = {{ cmdOutput.stdout }}"

    - name: Define expected values
      set_fact:
        expected_values:
          vnfc Ovld Level: "0"
          Process State: "STATE_INS_ACTIVE"
          vnfcHAMode: ["ACTIVE", "HOT_STANDBY"]
          LCM Event: "Start Success"
          vnfcState: "Configured Active"

    - name: Extract and check values
      block:
        - name: Extract values from output
          set_fact:
            extracted_values: "{{ extracted_values | default({}) | combine({item.key: cmdOutput.stdout | regex_search(item.key + ' : (.*)', '\\1') | trim}) }}"
          loop: "{{ expected_values | dict2items }}"

        - name: Check values
          set_fact:
            # Just to raise the event I have coded as extracted_values[item.key] not in item.value
            # This should be changed as extracted_values[item.key] in item.value
            generate_event: "{{ (item.value | type_debug == 'str' and extracted_values[item.key] != item.value) or (item.value | type_debug == 'list' and extracted_values[item.key] not in item.value) }}"
          loop: "{{ expected_values | dict2items }}"
          register: check_results

    - name: STATUS
      debug:
        msg:
          {
            "GENERATE_EVENT": "{{ true if check_results.results | selectattr('ansible_facts.generate_event') | list | length > 0 else false }}",
            "Additional Info": "{{ check_results.results | selectattr('ansible_facts.generate_event') | map(attribute='item.key') | join(', ') }}"
          }

