---
- name: "{{ EID_008_DESCRIPTION }}"
  hosts: remote_machines
  gather_facts: no
  vars_files:
    - vars_working.yml

  tasks:
    - name: Get core files
      raw: kubectl exec {{ pod_name }} -n {{ namespace }} -- {{ EID_008_CMD }}
      register: core_files
      ignore_errors: yes

    - name: Set core_files_lines
      set_fact:
        core_files_lines: "{{ core_files.stdout_lines | select('match', '^[-]') | list }}"

    - name: Set generate_event and additional_info
      set_fact:
        generate_event: "{{ core_files_lines | length > 0 }}"
        additional_info: "{{ core_files_lines }}"

    - name: STATUS
      debug:
        msg:
          {
            "GENERATE_EVENT": "{{ generate_event }}",
            "Additional Info": "{{ additional_info if generate_event else [] }}"
          }
