---
- name: XA cdr transferred file check
  hosts: remote_machines
  gather_facts: no
  vars_files:
    - vars_working.yml

  vars:
    CHECK_428_429_LAST_GENERATED_CDR_TIME_MIN: 35
    CHECK_428_429_CDR_CNF_NAMES: "CNF01,CNF02"
    CHECK_428_429_CDR_UNIQ_VNF_COUNT: 12
    additional_info: []
    GENERATE_EVENT: false

  tasks:

  - name: Find CDR temp files modified in last N minutes
    shell: |
      find /var/data/cdr/_transferred -type f -mmin -{{ CHECK_428_429_LAST_GENERATED_CDR_TIME_MIN }}
    register: cdr_files
    changed_when: false
    failed_when: false

  - name: Check each CNF for unique VNF count
    set_fact:
      additional_info: >-
        {{
          additional_info + [{
            'INFO': cnf + ' is having more/less than ' + CHECK_428_429_CDR_UNIQ_VNF_COUNT | string + ' vnf under cdr transferred [vnf count: ' + vnf_count | string + '].',
            'STATE': 'NOK',
            'CHECK': 'XA cdr transferred file check'
          }]
        }}
      GENERATE_EVENT: true
    vars:
      cnf_list: "{{ CHECK_428_429_CDR_CNF_NAMES.split(',') }}"
      vnf_count: >-
        {{
          cdr_files.stdout_lines
          | select("search", cnf)
          | map("regex_search", "_([0-9]+)_", "\\1")
          | select("string")
          | list
          | unique
          | length
        }}
    loop: "{{ cnf_list }}"
    loop_control:
      loop_var: cnf
    when: >-
      (cdr_files.stdout_lines | select("search", cnf)
       | map("regex_search", "_([0-9]+)_", "\\1")
       | select("string")
       | list
       | unique
       | length) != CHECK_428_429_CDR_UNIQ_VNF_COUNT

  - name: Set OK status if all CNFs have expected VNF count
    set_fact:
      additional_info: >-
        [{
          'INFO': '',
          'STATE': 'OK',
          'CHECK': 'XA cdr transferred file check'
        }]
    when: additional_info | length == 0

  - name: STATUS
    debug:
      msg:
        GENERATE_EVENT: "{{ GENERATE_EVENT }}"
        Additional_Info: "{{ additional_info }}"
