---
- name: K8s UCCAS App-wise Port Check
  hosts: remote_machines
  gather_facts: no
  vars_files:
    - vars_working.yml

  vars:
    additional_info: []
    GENERATE_EVENT: false

  tasks:

  - name: Check if port 10430 is in LISTEN mode
    raw: kubectl exec {{ pod_name_gtre }} -n {{ namespace }} -- netstat -anW 2>/dev/null | egrep ":10430 " | grep LISTEN | grep http
    register: port_check
    changed_when: false
    failed_when: false  # Prevent failure if no output

#  - name: Stub port check output to simulate LISTEN mode (for testing)
#    set_fact:
#      port_check:
#        stdout: "tcp 0 0 0.0.0.0:10430 0.0.0.0:* LISTEN"

  - name: Set NOK if no ports are found in LISTEN mode
    set_fact:
      additional_info: >-
        {{
          [{
            'INFO': 'No ports are found in LISTEN mode',
            'STATE': 'NOK',
            'CHECK': 'K8s UCCAS App wise port check'
          }]
        }}
      GENERATE_EVENT: true
    when: port_check.stdout | trim == ""

  - name: Set OK status if ports are found
    set_fact:
      additional_info: >-
        {{
          [{
            'INFO': '',
            'STATE': 'OK',
            'CHECK': 'K8s UCCAS App wise port check'
          }]
        }}
    when: port_check.stdout | trim != ""

  - name: STATUS
    debug:
      msg:
        GENERATE_EVENT: "{{ GENERATE_EVENT }}"
        Additional_Info: "{{ additional_info }}"
