---
- name: SM IPtables status check
  hosts: remote_machines
  gather_facts: no
  vars_files:
    - vars_working.yml

  vars:
    additional_info: []
    GENERATE_EVENT: false

  tasks:

  - name: Run iptables command to check for DROP rules
    raw: /usr/sbin/iptables -nL
    register: iptables_output
    changed_when: false
    failed_when: false

#  - name: Stub iptables output to simulate DROP rule (for testing)
#    set_fact:
#      iptables_output:
#        stdout: "Chain INPUT (policy ACCEPT)\nDROP       all  --  192.168.1.100        0.0.0.0/0"

  - name: Set NOK if DROP rules are found
    set_fact:
      additional_info: >-
        {{
          [{
            'INFO': 'NOK: Dropping traffic.',
            'STATE': 'NOK',
            'CHECK': 'SM IPtables status check'
          }]
        }}
      GENERATE_EVENT: true
    when: "'DROP' in iptables_output.stdout"

  - name: Set OK status if no DROP rules are found
    set_fact:
      additional_info: >-
        {{
          [{
            'INFO': '',
            'STATE': 'OK',
            'CHECK': 'SM IPtables status check'
          }]
        }}
    when: "'DROP' not in iptables_output.stdout"

  - name: STATUS
    debug:
      msg:
        GENERATE_EVENT: "{{ GENERATE_EVENT }}"
        Additional_Info: "{{ additional_info }}"

