---
- name: Check K8s MTU Size
  hosts: remote_machines
  vars_files:
    - vars_working.yml
  tasks:
    - name: Get MTU size of FP interfaces
      raw: kubectl exec {{ pod_name_vlbfe }} -n {{ namespace }} -- ip a | grep -i fp | grep -i mtu | awk '{print $2":"$5}'
      register: mtu_sizes

    - name: Print read_shm_output
      debug:
        var: mtu_sizes

    - name: Set MTU values
      set_fact:
        #mtu_values: "{{ mtu_sizes.stdout_lines | map('regex_replace', '.*:(\\d+)', '\\1') | map('int') }}"
        mtu_values: "{{ mtu_sizes.stdout_lines | map('regex_replace', '.*::(\\d+)', '\\1') | list }}"

    - name: Set MTU value int
      set_fact:
        mtu_value_int: "{{ mtu_values[0] | int }}"

    - name: Set MTU size status
      set_fact:
        mtu_size_status: "{{ 'OK' if mtu_values | unique | length == 1 and mtu_value_int == CHECK_416_K8S_MTU_SIZE else 'NOK' }}"

    - name: Set additional info
      set_fact:
        additional_info: "{{ mtu_sizes.stdout_lines | join(',') if mtu_size_status == 'NOK' else '' }}"

    - name: Print STATUS
      debug:
        msg:
          GENERATE_EVENT: "{{ mtu_size_status == 'NOK' }}"
          Additional Info: "{{ [{'CHECK': 'K8s MTU Size Check', 'STATE': mtu_size_status, 'INFO': additional_info if mtu_size_status == 'NOK' else ''}] | to_json }}"
