---
- name: Worker Hardware Error Check
  hosts: remote_machines
  gather_facts: no
  vars_files:
    - vars_working.yml

  vars:
    additional_info: []
    GENERATE_EVENT: false

  tasks:

  - name: Check for Worker Hardware Error Check
    #shell: zcat /var/log/pf9/kubelet/kubelet.*.root.log.ERROR*.gz | grep -aic 'PLEG is not healthy'
    shell: cat /var/log/messages | grep -aic 'Hardware Error'
    become: true
    register: hw_error_count
    changed_when: false
    failed_when: false

#  - name: Stub PLEG error count for testing
#    set_fact:
#      hw_error_count:
#        stdout: "5"

  - name: Set NOK if PLEG errors are found
    set_fact:
      additional_info: >-
        {{
          [{
            'INFO': 'PLEG is not healthy error count = ' + hw_error_count.stdout,
            'STATE': 'NOK',
            'CHECK': 'Worker Hardware Error Check'
          }]
        }}
      GENERATE_EVENT: true
    when: hw_error_count.stdout | int > 0

  - name: Set OK status if no PLEG errors
    set_fact:
      additional_info: >-
        [{
          'INFO': '',
          'STATE': 'OK',
          'CHECK': 'Worker Hardware Error Check'
        }]
    when: hw_error_count.stdout | int == 0

  - name: STATUS
    debug:
      msg:
        GENERATE_EVENT: "{{ GENERATE_EVENT }}"
        Additional_Info: "{{ additional_info }}"

