---
- name: Node Port Status Check
  hosts: remote_machines
  gather_facts: no
  vars:
    IGNORE_NAMESPACE: "kube|default|mwppaas|pf9|platform9-system|luigi-snir-platform"
  tasks:
    - name: Get NodePort services
      shell: "kubectl get svc -A | grep NodePort | grep -i pending | awk '{print $1\":\"$2\":\"$5\":\"$6}'"
      register: node_port_services
      ignore_errors: yes

    - name: Filter out ignored namespaces
      set_fact:
        node_port_services_filtered: "{{ node_port_services.stdout_lines | reject('match', IGNORE_NAMESPACE) | list }}"

    - name: STATUS
      debug:
        msg:
          GENERATE_EVENT: "{{ node_port_services_filtered | length > 0 }}"
          Additional Info: "{{ [{'CHECK': 'K8s Node Port Status', 'STATE': (node_port_services_filtered | length == 0) | ternary('OK', 'NOK'), 'INFO': node_port_services_filtered | join('\n')}] | to_json }}"
