---
- name: Master Health Check Script
  hosts: remote_machines
  gather_facts: yes
  vars_files:
    - vars_working.yml
  
  tasks:
    - name: Initialize results list
      set_fact:
        health_check_results: []

    - name: Execute EID_001 - ReadShm Status Check
      include: EID_001_readShm.yml
      vars:
        current_pod: "{{ pod_name }}"
        current_namespace: "{{ namespace }}"

    - name: Add EID_001 result to results list
      set_fact:
        health_check_results: "{{ health_check_results + [{'ID': '1', 'Description': EID_001_DESCRIPTION, 'Result': eid_001_final_result}] }}"

    - name: Execute EID_002 - Uptime Status Check
      include: EID_002_uptime.yml
      vars:
        current_pod: "{{ pod_name }}"
        current_namespace: "{{ namespace }}"

    - name: Add EID_002 result to results list
      set_fact:
        health_check_results: "{{ health_check_results + [{'ID': '2', 'Description': EID_002_DESCRIPTION, 'Result': eid_002_final_result}] }}"

    - name: Execute EID_003 - Warm Process Status Check
      include: EID_003_warmProcess.yml
      vars:
        current_pod: "{{ pod_name }}"
        current_namespace: "{{ namespace }}"

    - name: Add EID_003 result to results list
      set_fact:
        health_check_results: "{{ health_check_results + [{'ID': '3', 'Description': EID_003_DESCRIPTION, 'Result': eid_003_final_result}] }}"

    - name: Execute EID_004 - Log Level Config Status Check
      include: EID_004_logLevel.yml
      vars:
        current_pod: "{{ pod_name }}"
        current_namespace: "{{ namespace }}"

    - name: Add EID_004 result to results list
      set_fact:
        health_check_results: "{{ health_check_results + [{'ID': '4', 'Description': EID_004_DESCRIPTION, 'Result': eid_004_final_result}] }}"

    - name: Execute EID_005 - Disk Space Status Check
      include: EID_005_diskSpace.yml
      vars:
        current_pod: "{{ pod_name }}"
        current_namespace: "{{ namespace }}"

    - name: Add EID_005 result to results list
      set_fact:
        health_check_results: "{{ health_check_results + [{'ID': '5', 'Description': EID_005_DESCRIPTION, 'Result': eid_005_final_result}] }}"

    - name: Create CSV header
      lineinfile:
        path: "./health_check_results.csv"
        line: "ID,Description,Result"
        create: yes
        state: present
      delegate_to: localhost

    - name: Write results to CSV file
      lineinfile:
        path: "./health_check_results.csv"
        line: "{{ item.ID }},{{ item.Description }},{{ item.Result }}"
        state: present
      with_items: "{{ health_check_results }}"
      delegate_to: localhost

    - name: Display final results
      debug:
        msg: "Health Check Results: {{ health_check_results }}"

    - name: Display summary
      debug:
        msg: "Health check completed. Results saved to health_check_results.csv"
