---
- name: Master Health Check Script
  hosts: remote_machines
  gather_facts: yes
  vars_files:
    - vars_working.yml
  
  tasks:
    - name: Remove existing CSV file
      file:
        path: "./health_check_results.csv"
        state: absent
      delegate_to: localhost

    - name: Create CSV header
      lineinfile:
        path: "./health_check_results.csv"
        line: "ID,Description,Result"
        create: yes
        state: present
      delegate_to: localhost

    - name: Execute EID_001 - ReadShm Status Check
      include: EID_001_readShm.yml

    - name: Write EID_001 result to CSV
      lineinfile:
        path: "./health_check_results.csv"
        line: "1,{{ EID_001_DESCRIPTION }},{{ eid_001_final_result }}"
        state: present
      delegate_to: localhost

    - name: Execute EID_002 - Uptime Status Check
      include: EID_002_uptime.yml

    - name: Write EID_002 result to CSV
      lineinfile:
        path: "./health_check_results.csv"
        line: "2,{{ EID_002_DESCRIPTION }},{{ eid_002_final_result }}"
        state: present
      delegate_to: localhost

    - name: Execute EID_003 - Warm Process Status Check
      include: EID_003_warmProcess.yml

    - name: Write EID_003 result to CSV
      lineinfile:
        path: "./health_check_results.csv"
        line: "3,{{ EID_003_DESCRIPTION }},{{ eid_003_final_result }}"
        state: present
      delegate_to: localhost

    - name: Execute EID_004 - Log Level Config Status Check
      include: EID_004_logLevel.yml

    - name: Write EID_004 result to CSV
      lineinfile:
        path: "./health_check_results.csv"
        line: "4,{{ EID_004_DESCRIPTION }},{{ eid_004_final_result }}"
        state: present
      delegate_to: localhost

    - name: Execute EID_005 - Disk Space Status Check
      include: EID_005_diskSpace.yml

    - name: Write EID_005 result to CSV
      lineinfile:
        path: "./health_check_results.csv"
        line: "5,{{ EID_005_DESCRIPTION }},{{ eid_005_final_result }}"
        state: present
      delegate_to: localhost

    - name: Display results summary
      debug:
        msg: "Health check completed. Results saved to health_check_results.csv"

    - name: Show CSV contents
      command: cat ./health_check_results.csv
      register: csv_contents
      delegate_to: localhost

    - name: Display CSV contents
      debug:
        msg: "{{ csv_contents.stdout }}"
